### ISSUE TITLE
Bottles for Honey Blocks

### ISSUE THREAD

**Issue by pokemonrocks9** [Fliens/AutoCraft-Plugin#2]
The bottles do not come out with the recipe. they get deleted

**Comment by MrTransistorsChannel** [comment]
I'm planning on looking into this issue, currently crafting is being done using recipe book which (at least now) gives only the result of the craft and just deletes the incoming materials. Right now the only way I can think of is just force-checking if there's a honey bottle in the crafting recipe and manually adding empty bottles to the result array, but this needs checking because maybe there is a way to get what is left after the crafting is being done. 
### Please think about some other crafts that can have similar issue with lost items

**Comment by Fliens** [comment]
I've also thought of this but as @MrTransistorsChannel said, there is noe 'used' item in the crafting api. It is posible to implement but we would have to add a list of 'used' items like bottles, buckets... and test if one of these items is in the recipe. After successfully crafting, the 'used' item would drop out of the dispenser

**Comment by MrTransistorsChannel** [comment]
Ok so this may be a little bit off topic.
Latest stable Spigot BuildTools is now 1.17, they just forgot to change the info on their website, so I think that first we will update the plugin to 1.17 and then fix this issue because people want this plugin to be on 1.17 as soon as possible

**Comment by avixk** [comment]
Fixed this issue in https://github.com/Fliens/AutoCraft/pull/5 . I found a little method in the Material class called "getCraftingRemainingItem()" that is used to get remaining items from crafting ingredients. My edits check if there's a remaining item, and makes sure there's enough room for both the product and the remaining items in the output container.

**Comment by MrTransistorsChannel** [comment]
This can be closed now, got fixed in #8

**Comment by pokemonrocks9** [comment]
will the jar be updated to accommodate the change? It appears the current one is still the same

**Comment by MrTransistorsChannel** [comment]
Yeah, @Fliens you should update the spigot page and github release, the plugin is currently v2.2

**Comment by Fliens** [comment]
@pokemonrocks9 @MrTransistorsChannel release has been updated

**Comment by MrTransistorsChannel** [comment]
> @pokemonrocks9 @MrTransistorsChannel release has been updated

@Fliens please remove "added missing recipes" from the Spigot page (I fixed the release note on github already) so people won't spam issues. They will be added soon, I'm working on it for the next release
Sorry for continuing this thread
